//! F23: Electoral Compliance Reporting Agent
//!
//! Automates electoral compliance reporting by tracking expenditures,
//! donations, and activities against regulatory requirements.
//! Uses LLM to generate compliance reports and check actions against electoral law.

use dioxus::prelude::*;

/// A section within a compliance report.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ComplianceSection {
    pub title: String,
    pub content: String,
    pub compliant: bool,
    pub notes: String,
}

/// A full compliance report generated by the LLM.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ComplianceReport {
    pub id: String,
    pub report_type: String,
    pub period: String,
    pub content: Vec<ComplianceSection>,
    pub status: String,
    pub created_at: String,
}

/// Result of a compliance check on a specific action.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ComplianceCheckResult {
    pub action: String,
    pub compliant: bool,
    pub explanation: String,
    pub relevant_laws: Vec<String>,
    pub recommendations: Vec<String>,
}

/// System prompt for compliance report generation.
const REPORT_SYSTEM_PROMPT: &str = "\
You are an expert electoral compliance analyst. Your job is to generate detailed \
compliance reports for political campaigns based on the provided data.

You MUST respond with valid JSON matching this exact schema:
{
  \"sections\": [
    {
      \"title\": \"Section Title\",
      \"content\": \"Detailed analysis text\",
      \"compliant\": true,
      \"notes\": \"Any additional observations\"
    }
  ],
  \"status\": \"compliant\" or \"non_compliant\" or \"needs_review\"
}

Analyze the provided campaign data against relevant electoral regulations. \
Be thorough, cite specific regulatory requirements, and flag any potential issues. \
Each section should cover a distinct compliance area relevant to the report type.";

/// System prompt for compliance checking.
const CHECK_SYSTEM_PROMPT: &str = "\
You are an expert in electoral law and campaign finance regulations. \
When given a description of a campaign action, you must assess whether it complies \
with common electoral laws and regulations.

You MUST respond with valid JSON matching this exact schema:
{
  \"compliant\": true,
  \"explanation\": \"Detailed explanation of the compliance assessment\",
  \"relevant_laws\": [\"List of relevant laws or regulations\"],
  \"recommendations\": [\"List of recommended actions\"]
}

Be specific about which regulations apply. If the action is potentially non-compliant, \
explain exactly why and what steps should be taken to remedy the situation.";

/// Generate a compliance report using LLM analysis of campaign data.
#[server(endpoint = "compliance-reporting/generate-report")]
pub async fn generate_compliance_report(
    report_type: String,
    period: String,
    campaign_data: String,
) -> Result<ComplianceReport, ServerFnError> {
    use crate::infrastructure::llm::LlmMessage;
    use crate::infrastructure::{LlmClient, ServerState};
    use dioxus::fullstack::FullstackContext;

    let state: ServerState = FullstackContext::extract()
        .await
        .map_err(|e| ServerFnError::new(format!("{e:?}")))?;

    if report_type.trim().is_empty() {
        return Err(ServerFnError::new("Report type is required"));
    }
    if period.trim().is_empty() {
        return Err(ServerFnError::new("Reporting period is required"));
    }
    if campaign_data.trim().is_empty() {
        return Err(ServerFnError::new("Campaign data is required"));
    }

    let pool = state.db.pool();
    let llm = LlmClient::new(
        &state.llm_config.base_url,
        &state.llm_config.model,
        state.llm_config.timeout_secs,
        state.llm_config.max_retries,
    );

    let user_prompt = format!(
        "Generate a {report_type} compliance report for the period: {period}\n\n\
        Campaign data to analyze:\n{campaign_data}\n\n\
        Provide a thorough compliance analysis with multiple sections covering all \
        relevant regulatory areas for this type of report."
    );

    let messages = vec![
        LlmMessage {
            role: "system".to_string(),
            content: REPORT_SYSTEM_PROMPT.to_string(),
        },
        LlmMessage {
            role: "user".to_string(),
            content: user_prompt,
        },
    ];

    let start = std::time::Instant::now();

    let response = llm
        .generate(&messages, None, Some(0.3), Some(2048))
        .await
        .map_err(|e| ServerFnError::new(format!("LLM error: {e}")))?;

    let latency_ms = start.elapsed().as_millis() as i32;

    let _ = crate::infrastructure::log_llm_usage(
        pool,
        "compliance_reporting",
        &state.llm_config.model,
        response.prompt_tokens,
        response.completion_tokens,
        latency_ms,
    )
    .await;

    // Parse the LLM JSON response
    let raw = response.content.trim();
    // Try to extract JSON from markdown code block if present
    let json_str = if let Some(start_idx) = raw.find('{') {
        if let Some(end_idx) = raw.rfind('}') {
            &raw[start_idx..=end_idx]
        } else {
            raw
        }
    } else {
        raw
    };

    let parsed: serde_json::Value = serde_json::from_str(json_str)
        .map_err(|e| ServerFnError::new(format!("Failed to parse LLM response as JSON: {e}")))?;

    let sections: Vec<ComplianceSection> = parsed
        .get("sections")
        .and_then(|s| s.as_array())
        .map(|arr| {
            arr.iter()
                .map(|s| ComplianceSection {
                    title: s["title"].as_str().unwrap_or("Untitled").to_string(),
                    content: s["content"].as_str().unwrap_or("").to_string(),
                    compliant: s["compliant"].as_bool().unwrap_or(false),
                    notes: s["notes"].as_str().unwrap_or("").to_string(),
                })
                .collect()
        })
        .unwrap_or_default();

    let status = parsed
        .get("status")
        .and_then(|s| s.as_str())
        .unwrap_or("needs_review")
        .to_string();

    let report_id = uuid::Uuid::new_v4().to_string();
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();

    tracing::info!(
        report_id = %report_id,
        report_type = %report_type,
        sections = sections.len(),
        status = %status,
        latency_ms = latency_ms,
        "Compliance report generated"
    );

    Ok(ComplianceReport {
        id: report_id,
        report_type,
        period,
        content: sections,
        status,
        created_at: now,
    })
}

/// List all compliance reports.
///
/// Currently returns an empty list as database persistence for compliance reports
/// has not been implemented yet.
#[server(endpoint = "compliance-reporting/list-reports")]
pub async fn list_compliance_reports() -> Result<Vec<ComplianceReport>, ServerFnError> {
    use crate::infrastructure::ServerState;
    use dioxus::fullstack::FullstackContext;

    let _state: ServerState = FullstackContext::extract()
        .await
        .map_err(|e| ServerFnError::new(format!("{e:?}")))?;

    Ok(Vec::new())
}

/// Check whether a specific campaign action is compliant with electoral law.
#[server(endpoint = "compliance-reporting/check-compliance")]
pub async fn check_compliance(
    action_description: String,
) -> Result<ComplianceCheckResult, ServerFnError> {
    use crate::infrastructure::llm::LlmMessage;
    use crate::infrastructure::{LlmClient, ServerState};
    use dioxus::fullstack::FullstackContext;

    let state: ServerState = FullstackContext::extract()
        .await
        .map_err(|e| ServerFnError::new(format!("{e:?}")))?;

    if action_description.trim().is_empty() {
        return Err(ServerFnError::new("Action description is required"));
    }

    let pool = state.db.pool();
    let llm = LlmClient::new(
        &state.llm_config.base_url,
        &state.llm_config.model,
        state.llm_config.timeout_secs,
        state.llm_config.max_retries,
    );

    let user_prompt = format!(
        "Assess the following campaign action for compliance with electoral law:\n\n\
        Action: {action_description}\n\n\
        Provide a thorough compliance assessment."
    );

    let messages = vec![
        LlmMessage {
            role: "system".to_string(),
            content: CHECK_SYSTEM_PROMPT.to_string(),
        },
        LlmMessage {
            role: "user".to_string(),
            content: user_prompt,
        },
    ];

    let start = std::time::Instant::now();

    let response = llm
        .generate(&messages, None, Some(0.2), Some(1024))
        .await
        .map_err(|e| ServerFnError::new(format!("LLM error: {e}")))?;

    let latency_ms = start.elapsed().as_millis() as i32;

    let _ = crate::infrastructure::log_llm_usage(
        pool,
        "compliance_reporting",
        &state.llm_config.model,
        response.prompt_tokens,
        response.completion_tokens,
        latency_ms,
    )
    .await;

    // Parse the LLM JSON response
    let raw = response.content.trim();
    let json_str = if let Some(start_idx) = raw.find('{') {
        if let Some(end_idx) = raw.rfind('}') {
            &raw[start_idx..=end_idx]
        } else {
            raw
        }
    } else {
        raw
    };

    let parsed: serde_json::Value = serde_json::from_str(json_str)
        .map_err(|e| ServerFnError::new(format!("Failed to parse LLM response as JSON: {e}")))?;

    let compliant = parsed
        .get("compliant")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    let explanation = parsed
        .get("explanation")
        .and_then(|v| v.as_str())
        .unwrap_or("No explanation provided")
        .to_string();

    let relevant_laws: Vec<String> = parsed
        .get("relevant_laws")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    let recommendations: Vec<String> = parsed
        .get("recommendations")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    tracing::info!(
        compliant = compliant,
        latency_ms = latency_ms,
        "Compliance check completed"
    );

    Ok(ComplianceCheckResult {
        action: action_description,
        compliant,
        explanation,
        relevant_laws,
        recommendations,
    })
}
