import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.rs",
    "./assets/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        navy: {
          50:  "#f0f3f9",
          100: "#dce3f0",
          200: "#b8c7e1",
          300: "#8ea5cd",
          400: "#6583b8",
          500: "#4a669e",
          600: "#3a5080",
          700: "#2f4068",
          800: "#243255",
          900: "#1b2642",
          950: "#111830",
        },
        civic: {
          50:  "#eff8ff",
          100: "#dbeffe",
          200: "#bfe3fe",
          300: "#93d2fd",
          400: "#60b8fa",
          500: "#3b9af6",
          600: "#257ceb",
          700: "#1d65d8",
          800: "#1e52af",
          900: "#1e478a",
          950: "#172c54",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        "politiktok-dark": {
          "primary":          "#3b9af6",
          "primary-content":  "#ffffff",
          "secondary":        "#4a669e",
          "secondary-content":"#ffffff",
          "accent":           "#60b8fa",
          "accent-content":   "#111830",
          "neutral":          "#1e293b",
          "neutral-content":  "#cbd5e1",
          "base-100":         "#0f172a",
          "base-200":         "#1e293b",
          "base-300":         "#334155",
          "base-content":     "#e2e8f0",
          "info":             "#38bdf8",
          "info-content":     "#002b3d",
          "success":          "#22c55e",
          "success-content":  "#002b10",
          "warning":          "#f59e0b",
          "warning-content":  "#1c1300",
          "error":            "#ef4444",
          "error-content":    "#ffffff",
        },
      },
      {
        "politiktok-light": {
          "primary":          "#1d65d8",
          "primary-content":  "#ffffff",
          "secondary":        "#3a5080",
          "secondary-content":"#ffffff",
          "accent":           "#257ceb",
          "accent-content":   "#ffffff",
          "neutral":          "#f1f5f9",
          "neutral-content":  "#334155",
          "base-100":         "#ffffff",
          "base-200":         "#f8fafc",
          "base-300":         "#e2e8f0",
          "base-content":     "#1e293b",
          "info":             "#0ea5e9",
          "info-content":     "#ffffff",
          "success":          "#16a34a",
          "success-content":  "#ffffff",
          "warning":          "#d97706",
          "warning-content":  "#ffffff",
          "error":            "#dc2626",
          "error-content":    "#ffffff",
        },
      },
    ],
    darkTheme: "politiktok-dark",
  },
};
